openapi: 3.0.1
info:
  title: Main Openapi Yaml
  version: 0.1.0
servers:
- url: "{server}:{port}/"
  variables:
    server:
      default: http://localhost
    port:
      default: port
paths:
  /greeting:
    post:
      operationId: postGreeting
      responses:
        "201":
          description: Created
          content:
            text/plain:
              schema:
                type: string
